### ISSUE TITLE
Clicking the text to add a comment, the "leave a comment" text remains http://take.ms/JSo65

### ISSUE THREAD

**Issue by austenallred** [grasswire/Issues#14]

**Comment by austenallred** [comment]
http://take.ms/JSo65

**Comment by levinotik** [comment]
![grasswire__the_internets_newsroom_27_08-58-07](https://cloud.githubusercontent.com/assets/514174/6416186/339fadd6-be72-11e4-83ea-4b55579e08dc.png)
