### ISSUE TITLE
Checkmark on new username appears on top of x in input

### ISSUE THREAD

**Issue by levinotik** [grasswire/Issues#6]
Browser: IE 10
OS: Windows 7

![screen shot 2015-02-26 at 12 20 00 pm](https://cloud.githubusercontent.com/assets/514174/6397336/f6c5afac-bdb1-11e4-88b2-e9a3ce4f40a9.png)

**Comment by JoeCianflone** [comment]
```
 ::-ms-clear {
      display: none;
  }
```
IE's version of Clippy has been removed
